---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-uaac
    tag: latest

inputs:
- name: uaa-pipeline-repo

run:
  path: uaa-pipeline-repo/ci/tasks/test-uaa.sh

params:
  APP_NAME:
  CF_APP_DOMAIN:
  ADMIN_SECRET:
  USER_PASSWORD:
  SKIP_CERT_CHECK:
