---
resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: latest

- name: terraform
  type: docker-image
  source:
    repository: engineerbetter/cf-terraform-image

resources:
- name: uaa-war
  type: maven-resource
  source:
    url: https://repo1.maven.org/maven2
    artifact: org.cloudfoundry.identity:cloudfoundry-identity-uaa:war

- name: uaa-pipeline-repo
  type: git
  source:
    uri: https://github.com/engineerbetter/uaa-pipeline.git
    branch: master
    paths:
    - assets/uaa_manifest.yml
    - terraform/*
    - ci/tasks/*

- name: cf-tf
  type: terraform
  source:
    storage:
      bucket: ((tf_bucket_name))
      bucket_path: terraform/
      region_name: eu-west-2
      access_key_id: ((concourse_ci_s3_access_key))
      secret_access_key: ((concourse_ci_s3_secret_key))
    env:
      HOME: /root

- name: cf
  type: cf
  source:
    api: ((cf_api))
    username: ((cf_username))
    password: ((cf_password))
    organization: ((cf_org))
    space: ((cf_space))
    skip_cert_check: ((skip_cert_check))

jobs:
- name: terraform-cf
  plan:
  - get: uaa-pipeline-repo
    trigger: true
  - put: cf-tf
    params:
      env_name: local
      terraform_source: uaa-pipeline-repo/terraform/
      vars:
        cf_api: ((cf_api))
        cf_username: ((cf_username))
        cf_password: ((cf_password))
        cf_org: ((cf_org))
        cf_space: ((cf_space))
        cf_service_name: ((cf_service_name))
        cf_service_plan: ((cf_service_plan))

- name: deploy-uaa
  serial: true
  plan:
  - get: uaa-pipeline-repo
    trigger: true
    passed:
    - terraform-cf
  - get: uaa-war
    trigger: true
  - get: cf-tf
    trigger: true
    passed:
    - terraform-cf
  - task: build-manifest
    file: uaa-pipeline-repo/ci/tasks/build-manifest.yml
    params:
      UAA_APP_NAME: ((uaa_app_name))
      CF_APP_DOMAIN: ((cf_app_domain))
      ADMIN_SECRET: ((admin_secret))
      USER_PASSWORD: ((user_password))
  - put: cf
    params:
      manifest: uaa-manifest/manifest.yml
      path: uaa-war/cloudfoundry-identity-uaa-*.war

- name: bootstrap-admin
  plan:
  - get: uaa-pipeline-repo
    trigger: true
    passed:
    - deploy-uaa
  - get: cf-tf
    trigger: true
    passed:
    - deploy-uaa
  - task: bootstrap-admin
    file: uaa-pipeline-repo/ci/tasks/bootstrap-admin.yml
    params:
      ADMIN_SECRET: ((admin_secret))
      APP_NAME: ((app_name))
      BOOTSTRAP_ADMIN_NAME: ((bootstrap_admin_name))
      BOOTSTRAP_ADMIN_SECRET: ((bootstrap_admin_secret))
      CF_APP_DOMAIN: ((cf_app_domain))
      SKIP_CERT_CHECK: ((skip_cert_check))

- name: test-uaa
  plan:
  - get: uaa-pipeline-repo
    trigger: true
    passed:
    - bootstrap-admin
  - get: cf-tf
    trigger: true
    passed:
    - bootstrap-admin
  - task: test-uaa
    file: uaa-pipeline-repo/ci/tasks/test-uaa.yml
    params:
      APP_NAME: ((app_name))
      CF_APP_DOMAIN: ((cf_app_domain))
      ADMIN_SECRET: ((admin_secret))
      USER_PASSWORD: ((user_password))
      SKIP_CERT_CHECK: ((skip_cert_check))
