---
resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: latest

- name: terraform
  type: docker-image
  source:
    repository: engineerbetter/cf-terraform-image

resources:
- name: uaa-war
  type: maven-resource
  source:
    url: https://repo1.maven.org/maven2
    artifact: org.cloudfoundry.identity:cloudfoundry-identity-uaa:war

- name: uaa-pipeline-repo
  type: git
  source:
    uri: https://github.com/engineerbetter/uaa-pipeline.git
    branch: master
    paths:
    - assets/uaa_manifest.yml
    - terraform/*

- name: cf-tf
  type: terraform
  source:
    storage:
      bucket: ((tf_bucket_name))
      bucket_path: terraform/
      region_name: eu-west-2
      access_key_id: ((concourse_ci_s3_access_key))
      secret_access_key: ((concourse_ci_s3_secret_key))
    env:
      HOME: /root

- name: cf
  type: cf
  source:
    api: ((cf_api))
    username: ((cf_username))
    password: ((cf_password))
    organization: ((cf_org))
    space: ((cf_space))
    skip_cert_check: ((skip_cert_check))

jobs:
- name: terraform-cf
  plan:
  - get: uaa-pipeline-repo
    trigger: true
  - put: cf-tf
    params:
      env_name: local
      terraform_source: uaa-pipeline-repo/terraform/
      vars:
        cf_api: ((cf_api))
        cf_username: ((cf_username))
        cf_password: ((cf_password))
        cf_org: ((cf_org))
        cf_space: ((cf_space))
        cf_service_name: ((cf_service_name))
        cf_service_plan: ((cf_service_plan))

- name: deploy-uaa
  serial: true
  plan:
  - get: uaa-pipeline-repo
    trigger: true
    passed:
    - terraform-cf
  - get: uaa-war
    trigger: true
  - get: cf-tf
    trigger: true
    passed:
    - terraform-cf
  - task: build-manifest
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: engineerbetter/pcf-ops
          tag: latest
      inputs:
      - name: uaa-pipeline-repo
      outputs:
      - name: uaa-manifest
      params:
        APP_NAME: ((uaa_app_name))
        CF_APP_DOMAIN: ((cf_app_domain))
        ADMIN_SECRET: ((admin_secret))
        USER_PASSWORD: ((user_password))
      run:
        path: bash
        args:
        - -euc
        - |
          sed "s/@appname@/$APP_NAME/g;s/@appdomain@/$CF_APP_DOMAIN/g;s/@adminsecret@/$ADMIN_SECRET/g;s/@userpassword@/$USER_PASSWORD/g" \
            uaa-pipeline-repo/assets/uaa_manifest.yml > uaa-manifest/manifest.yml
  - put: cf
    params:
      manifest: uaa-manifest/manifest.yml
      path: uaa-war/cloudfoundry-identity-uaa-*.war

- name: test-uaa
  plan:
  - get: uaa-pipeline-repo
    trigger: true
    passed:
    - deploy-uaa
  - get: cf-tf
    trigger: true
    passed:
    - deploy-uaa
  - task: test-uaa
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/cf-uaac
          tag: latest
      params:
        APP_NAME: ((uaa_app_name))
        CF_APP_DOMAIN: ((cf_app_domain))
        ADMIN_SECRET: ((admin_secret))
        USER_PASSWORD: ((user_password))
        SKIP_CERT_CHECK: ((skip_cert_check))
      run:
        path: sh
        args:
        - -euc
        - |
          echo "Log in to UAA"
          if [ "${SKIP_CERT_CHECK}" = "true" ]; then
            uaac target https://${APP_NAME}.${CF_APP_DOMAIN} --skip-ssl-validation
          else
            uaac target https://${APP_NAME}.${CF_APP_DOMAIN}
          fi

          echo "Check that admin client exists"
          uaac token client get admin -s ${ADMIN_SECRET}

          echo "Check that default account doesn't exist"
          set +e
          uaac token owner get cf marissa -s "" -p koala
          result=$?
          set -e
          if [ $result -eq 0 ]; then
            echo "default user should not exist" && exit 1
          fi

          echo "Check that the bootstrapped user exists..."
          uaac user get user -a username

          echo "... and can obtain a token..."
          uaac token owner get cf user -s "" -p ${USER_PASSWORD}

          echo "... and that the token is valid"
          uaac token decode
