---
resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: latest

- name: terraform
  type: docker-image
  source:
    repository: engineerbetter/cf-terraform-image

resources:
- name: uaa-war
  type: maven-resource
  source:
    url: https://repo1.maven.org/maven2
    artifact: org.cloudfoundry.identity:cloudfoundry-identity-uaa:war

- name: uaa-pipeline-repo
  type: git
  source:
    uri: https://github.com/engineerbetter/uaa-pipeline.git
    branch: master
    paths:
    - assets/uaa_manifest.yml
    - terraform/*

- name: cf-tf
  type: terraform
  source:
    storage:
      bucket: deejay-cf-tf
      bucket_path: terraform/
      region_name: eu-west-2
      access_key_id: ((concourse_ci_s3_access_key))
      secret_access_key: ((concourse_ci_s3_secret_key))
    env:
      HOME: /root

- name: cf
  type: cf
  source:
    api: https://api.local.pcfdev.io
    username: admin
    password: admin
    organization: pcfdev-org
    space: pcfdev-space
    skip_cert_check: true

jobs:
- name: terraform-cf
  plan:
  - get: uaa-pipeline-repo
    trigger: true
  - put: cf-tf
    params:
      env_name: local
      terraform_source: uaa-pipeline-repo/terraform/
      vars:
        cf_api: ((cf_api))
        cf_username: ((cf_username))
        cf_password: ((cf_password))

- name: deploy-uaa
  plan:
  - get: uaa-pipeline-repo
    trigger: true
    passed:
    - terraform-cf
  - get: uaa-war
    trigger: true
  - get: cf-tf
    trigger: true
    passed:
    - terraform-cf
  - task: build-manifest
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: engineerbetter/pcf-ops
          tag: latest
      inputs:
      - name: uaa-pipeline-repo
      outputs:
      - name: uaa-manifest
      params:
        APP_NAME: ((uaa_app_name))
        CF_APP_DOMAIN: ((cf_app_domain))
      run:
        path: bash
        args:
        - -euc
        - |
          sed "s/@app@/$APP_NAME/g;s/@appdomain@/$CF_APP_DOMAIN/g" uaa-pipeline-repo/assets/uaa_manifest.yml > uaa-manifest/manifest.yml
  - put: cf
    params:
      manifest: uaa-manifest/manifest.yml
      path: uaa-war/cloudfoundry-identity-uaa-*.war
